common/models/Fila.php
<?php

namespace common\models;

use Yii;
use yii\data\ActiveDataProvider;
use common\components\Setup;

/**
 * This is the model class for table "tb_cdr_fila".
 *
 * @property int $id
 * @property int $usuario_fk
 * @property int $unidade_fk
 * @property string $calldate
 * @property string $src
 * @property string $dst
 * @property int $atraso
 * @property int $duration
 * @property int $billsec
 * @property string $disposition
 *
 */
class Fila extends \yii\db\ActiveRecord
{
    
    public $pesquisa;
    
    public static function tableName()
    {
        return 'tb_cdr_fila';
    }

    public function rules()
    {
        return [
            [['usuario_fk', 'unidade_fk', 'atraso', 'duration', 'billsec'], 'integer'],
            [['calldate'], 'required'],
            [['calldate'], 'safe'],
            [['src', 'dst'], 'string', 'max' => 80],
            [['disposition'], 'string', 'max' => 45],
            [['unidade_fk'], 'exist', 'skipOnError' => true, 'targetClass' => Unidade::className(), 'targetAttribute' => ['unidade_fk' => 'id']],
            [['usuario_fk'], 'exist', 'skipOnError' => true, 'targetClass' => Usuario::className(), 'targetAttribute' => ['usuario_fk' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'usuario_fk' => 'Usuario',
            'unidade_fk' => 'Unindade',
            'calldate' => 'Calldate',
            'src' => 'Origem',
            'dst' => 'Destino',
            'atraso' => 'Espera',
            'duration' => 'Duração Total',
            'billsec' => 'Tempo de Converssa',
            'disposition' => 'Status',
        ];
    }
    
    public function getUnidadeFk()
    {
        return $this->hasOne(Unidade::className(), ['id' => 'unidade_fk']);
    }
    
    public function getUsuarioFk()
    {
        return $this->hasOne(Usuario::className(), ['id' => 'usuario_fk']);
    }
    
    public function afterFind() {
        parent::afterFind();
        if ($this->calldate) {
            $this->calldate = Setup::convertApresentacao($this->calldate, 'datetime');
        }
    }

    public function afterValidate() {
        parent::afterValidate();
        if ($this->calldate) {
            $this->calldate = Setup::convertBD($this->calldate, 'datetime');
        }
    }
    
    public function search($params) {
        $query = Fila::find()->select(['calldate','src', 'dst','atraso', 'duration','billsec', 'disposition'])->distinct();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'calldate' => SORT_ASC,
                ]
            ],
        ]);

        if (isset($params['Fila']['pesquisa'])) {
            $query->orFilterWhere(['like', 'UPPER(fc_remove_acento(src))', strtoupper(Setup::retirarAcento($params['Fila']['pesquisa']))])
                ->orFilterWhere(['like', 'UPPER(fc_remove_acento(dst))', strtoupper(Setup::retirarAcento($params['Fila']['pesquisa']))])
                ->orFilterWhere(['like', 'UPPER(fc_remove_acento(calldate))', strtoupper(Setup::retirarAcento($params['Fila']['pesquisa']))]);
        }
        
        if (Yii::$app->user->identity->hora_inicio != NULL){
            $hora_inicio = ' '.Yii::$app->user->identity->hora_inicio.':00:00';
        } else if (Yii::$app->user->identity->hora_inicio === 0){
            $hora_inicio = ' 00:00:00';
        } else {
            $hora_inicio = ' 00:00:00';
        }
        if (Yii::$app->user->identity->hora_fim != NULL){
            $hora_fim = ' '.Yii::$app->user->identity->hora_fim.':59:59';
        } else if (Yii::$app->user->identity->hora_fim === 0){
            $hora_fim = ' 00:59:59';
        } else {
            if (Yii::$app->user->identity->hora_inicio != NULL){
                $hora_fim = ' '.Yii::$app->user->identity->hora_inicio.':59:59';
            } else if (Yii::$app->user->identity->hora_inicio === 0){
                $hora_fim = ' 00:59:59';
            } else {
                $hora_fim = ' 23:59:59';
            }
        }
        $query->andFilterWhere(['=', 'usuario_fk', Yii::$app->user->identity->id]);
        $query->andFilterWhere(['=', 'unidade_fk', Yii::$app->user->identity->unidade_temp_fk]);
        $query->andFilterWhere(['>', 'calldate', Yii::$app->user->identity->data_asterisk.$hora_inicio]);
        $query->andFilterWhere(['<', 'calldate', Yii::$app->user->identity->data_asterisk.$hora_fim]);
        
        if (Yii::$app->user->identity->voip_origem) {
            $query->andFilterWhere(['=', 'src', Yii::$app->user->identity->voip_origem]);
        }
        
        if (Yii::$app->user->identity->voip_destino) {
            $query->andFilterWhere(['=', 'dst', Yii::$app->user->identity->voip_destino]);
        }
        
        if (Yii::$app->user->identity->status_chamada) {
            $query->andFilterWhere(['=', 'disposition', Yii::$app->user->identity->status_chamada]);
        }
        
        $query->andFilterWhere(['!=', 'dst', 's']);
        
        return $dataProvider;
    }
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Usuario;
use common\models\Sistema;
use common\components\Setup;
use common\models\UsuarioPerfil;
use common\components\SendMail;
use common\models\Computador;
use common\models\Monitor;
use common\models\Equipamento;

/**
 * Site controller
 */
class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'new-password', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'set-session-unidade', 'profile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        if (Yii::$app->session->isActive) {
            
            $url = Sistema::findOne(1);
            Yii::$app->session->set("url", $url->url);

        }
        

        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin() {
        $this->layout = "main_login";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';
            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->goHome();
    }
    
    public function actionSetSessionUnidade() {
        $model = Usuario::findOne(Yii::$app->user->identity->id);
        $request = Yii::$app->request->post();
        if ($model) {
            $model->unidade_temp_fk = $request['unidade_temp_fk'];
            $model->save();
        }
        Yii::$app->user->identity->unidade_temp_fk = $request['unidade_temp_fk'];
    }
    
    public function actionResetPassword() {
        $this->layout = "main_login";
        $model = new Usuario();

        if (Yii::$app->request->isAjax) {
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
        } else {
            if ($model->load(Yii::$app->request->post())) {
                $model = Usuario::find()->where(['email' => $model->email])->all();
                foreach ($model as $key => $value) {
                    $value->token = Yii::$app->security->generateRandomString();
                    if ($value->save()) {
                        Yii::$app->mailer->compose([
                                    'html' => 'novo_cadastro_insignare-html',
                                    'text' => 'novo_cadastro_insignare-text'
                                        ], [
                                    'model' => $value
                                ])->setFrom([
                                    'insignare@acpr.org.br' => 'Insignare'
                                ])->setTo($value->email)
                                ->setSubject('Atualização de senha!')
                                ->send();
                    } else {
                        throw new \Exception(Setup::setMessageErrorModel('Atenção:', $model->getErrors()));
                    }
                }
                Yii::$app->session->setFlash('success', 'Registro atualizado com sucesso!');
                return $this->redirect(['site/login']);
            } else {
                $model->senha = '';
            }
        }
        return $this->render('reset_password', [
                    'model' => $model,
        ]);
    }

    public function actionNewPassword($token) {
        $this->layout = "main_login";
        $model = Usuario::findOne(['token' => $token]);

        if ($model) {
            if (Yii::$app->request->isAjax) {
                if ($model->load(Yii::$app->request->post())) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($model);
                }
            } else {
                if ($model->load(Yii::$app->request->post())) {
                    $transaction = Yii::$app->db->beginTransaction();
                    try {
                        $model->senha = Yii::$app->security->generatePasswordHash($model->senha);
                        $model->senha_hash = $model->senha;
                        $model->auth_key = Yii::$app->security->generateRandomString();
                        $model->token = Yii::$app->security->generateRandomString();
                        if ($model->save()) {
                            $transaction->commit();
                            $emails = [ $model->email ];
                            SendMail::submitpassword($emails, $model, 'email_usuario_senha_atualizacao-html');
                            return $this->redirect(['site/login']);
                        } else {
                            throw new \Exception(Setup::setMessageErrorModel('Atenção:', $model->getErrors()));
                        }
                    } catch (\Exception $e) {
                        $mensagem = $e->getMessage();
                        $transaction->rollBack();
                        $model->load(Yii::$app->request->post());
                        Yii::$app->session->setFlash('error', $mensagem);
                    }
                } else {
                    $model->senha = '';
                }
            }
            return $this->render('new_password', [
                'model' => $model,
            ]);
        } else {
            return $this->goHome();
        }
    }
    
    public function actionProfile() {
        $model = Usuario::findOne(Yii::$app->user->identity->id);
        $model->senha = '';
        if (Yii::$app->request->isAjax) {
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
        } else {
            if ($model->load(Yii::$app->request->post())) {
                $model_anterior = Usuario::findOne(Yii::$app->user->identity->id);
                if ($model_anterior->senha != $model->senha){
                    $model->senha = Yii::$app->security->generatePasswordHash($model->senha);
                    $model->senha_hash = $model->senha;
                }
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'Registro alterado com sucesso!');
                    return $this->redirect(['site/profile']);
                }
            }
        }
        return $this->render('perfil', [
                    'title' => 'Editar meu Usuario',
                    'model' => $model,
        ]);
    }
    
}

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Home';
?>
<div class="site-index">

</div>

backend/views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class=" card-box">
    <div class="panel-heading"> 
        <h3 class="text-center"> <?php echo Html::encode($this->title) ?> </h3>
    </div> 

    <p>Por favor, preencha os seguintes campos para entrar:</p>

    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?php echo $form->field($model, 'username')->textInput(['autofocus' => true]); ?>

                <?php echo $form->field($model, 'password')->passwordInput(); ?>

                <div class="form-group">
                    <?php echo Html::submitButton('Entrar', ['class' => 'btn btn-primary', 'name' => 'login-button']); ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

backend/views/site/new_password.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Faça uma nova senha!';
?>
<div class="row">
    <div class="col-xs-12">
    </div>
    <div class="col-xs-12">
        <div class="card-box">

            <div class="panel-heading">
                <h3 class="text-left">Troca minha senha</h3>
            </div>
            <div class="panel-body">
                <?php $form = ActiveForm::begin(['id' => 'login-form', 'class' => 'form-horizontal m-t-20']); ?>
                <div class="form-group ">
                    <div class="col-xs-12">
                        <label class="control-label"><?php echo $model->getAttributeLabel('nome'); ?></label>
                        <input type="text" class="form-control" disabled="" value="<?php echo $model->nome; ?>">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-xs-12">
                        <label class="control-label"><?php echo $model->getAttributeLabel('email'); ?></label>
                            <input type="text" class="form-control" disabled="" value="<?php echo $model->email; ?>">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-xs-12">
                        <label class="control-label"><?php echo $model->getAttributeLabel('usuario'); ?></label>
                            <input type="text" class="form-control" disabled="" value="<?php echo $model->usuario; ?>">
                    </div>
                </div>
                <div class="form-group ">
                    <div class="col-xs-12">
                        <?php echo $form->field($model, 'senha')->passwordInput(['placeholder' => 'Sua Senha', 'class' => 'form-control'])->label(''); ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo Html::submitButton('Atualizar', ['class' => 'btn btn-primary btn-block text-uppercase waves-effect waves-light', 'name' => 'login-button']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-12">
    </div>
</div>

backend/views/site/perfil.php
<?php

use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use common\models\Unidade;

$this->title = 'Usuario';
?>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-border panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $title; ?></h3>
            </div>
            <div class="panel-body">

                <?php $form = ActiveForm::begin(); ?>

                <div class="row">
                    <div class="col-sm-6">
                        <?php echo $form->field($model, 'nome')->textInput(['class' => 'form-control', 'maxlength' => true, 'autofocus' => true]) ?>
                    </div>
                    <div class="col-sm-6">
                        <?php echo $form->field($model, 'email')->textInput(['class' => 'form-control', 'maxlength' => true]) ?>
                    </div>            
                </div>
                <div class="row">
                    <div class="col-sm-5">
                        <?php echo $form->field($model, 'senha')->passwordInput(['class' => 'form-control', 'maxlength' => true, 'onkeyup' => 'javascript:verifica_forca(this.value)']) ?>
                    </div>
                    <div class="col-sm-1">
                        <br>
                        <span id="mostra"></span>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label"><?php echo $model->getAttributeLabel('unidade'); ?></label>
                            <input type="text" class="form-control" disabled="" value="<?php echo $model->unidadeFk->unidade; ?>">
                        </div>                                        
                    </div>
                </div>
                <div class="form-group text-right m-b-0">
                    <?php echo Html::submitButton($model->isNewRecord ? Yii::t('app', '<i class="ion-checkmark-round"></i> Salvar') : Yii::t('app', '<i class="ion-checkmark-round"></i> Salvar'), ['class' => 'btn btn-primary waves-effect waves-light']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

<?php
    $this->registerJs("
        function verifica_forca(senha){
            forca = 0;
            mostra = document.getElementById('mostra');
            if((senha.length > 7) && (senha.length <= 12)){
                forca += 10;
            }else if((senha.length>12)){
                forca += 25;
            }
            if(senha.match(/[a-z]+/)){
                forca += 10;
            }
            if(senha.match(/[A-Z]+/)){
                forca += 20;
            }
            if(senha.match(/\d+/)){
                forca += 20;
            }
            if(senha.match(/\W+/)){
                forca += 25;
            }
            return mostra_res();
            return libera_aplicar();
        }
        function mostra_res(){
            if(forca <=30){
                mostra.innerHTML = '<span style=\"color:#FF0000;\"> Fraca </span>';
            }else if((forca > 30) && (forca < 60)){
                mostra.innerHTML = '<span style=\"color:#FFBE00;\"> Boa </span>'; 
            }else if((forca >= 60) && (forca < 85)){
                mostra.innerHTML = '<span style=\"color:#0000FF;\"> Forte </span>';
            }else {
                mostra.innerHTML = '<span style=\"color:#00CD00;\"> Excelente </span>';
            }
        }
       ", View::POS_END, 'functions-usuario-password'
    );
?>